language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t tchorzewski1991/react-multidocker-travis-aws-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tchorzewski1991/react-multidocker-travis-aws-test npm run test

after_success:
  - docker build -t tchorzewski1991/react-multidocker-travis-aws-client ./client 
  - docker build -t tchorzewski1991/react-multidocker-travis-aws-server ./server 
  - docker build -t tchorzewski1991/react-multidocker-travis-aws-worker ./worker 
  - docker build -t tchorzewski1991/react-multidocker-travis-aws-nginx  ./nginx 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push tchorzewski1991/react-multidocker-travis-aws-client
  - docker push tchorzewski1991/react-multidocker-travis-aws-server
  - docker push tchorzewski1991/react-multidocker-travis-aws-worker
  - docker push tchorzewski1991/react-multidocker-travis-aws-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: react-docker-travis-aws
  env: ReactMultiDockerTravisAws-env
  bucket_name: elasticbeanstalk-us-east-2-653534635463
  bucket_path: react-multidocker-travis-aws
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
